### PR TITLE
fix: make sure nics are enable

### PR DESCRIPTION
**Pull request by jfroche**
New machines created from a template sometimes don't have its network
interfaces connected to the network. This happen for example when
terraform customize the template after cloning.

To fix this issue, we do the same as DataSourceOVF[1] and make sure that
the interfaces defined by vmware-imc connect using vmware-rpctool.

similar issue: https://github.com/vmware/open-vm-tools/issues/299

[1]: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceOVF.py#L261

### CODE REVIEW

**Comment by prologic** [comment]
Why is this not merged?

**Comment by akutz** [comment]
> Why is this not merged?

Because it:

* has merge conflicts
* uses a working branch in the install script instead of the real one
* was partially resolved on a different PR and has never been updated

**Comment by prologic** [comment]
Where was this partially solved elsewhere?

**Comment by akutz** [comment]
> Where was this partially solved elsewhere?

#51, #53, and #54 all address the subp logic this PR also addresses. If this PR rebases on main, fixes the conflicts, and then squashes its commits, it can be considered for merge.

**Comment by akutz** [comment]
If you are interested in seeing this merged and would like to open a PR with this, addressing the above issues, please do so, and I will review in the morning (it's just past midnight here).

**Comment by prologic** [comment]
Thanks will do! I'm still trying to figure out and understand why when I Terraform up some vSphere virtual machines resources from a template with customisations the NC(s) are left in a "disconnected" state. This only seems to happen when `disable_vmware_customize: false` appears in `/etc/cloud/cloud.cfg` which is read by `vmtoolsd` from vmware/open-vm-tools -- I'm avoiding that code-path for the time being by commenting out the `customization { ...}` in my Terraform specs.

If it turns out this PR is still needed, I'll happily clean it up and re-submit a PR based off this work.

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!

**Pull request closed without merging**
